const regions = [
    {"code": "01", "description": "Guadeloupe"},
    {"code": "02", "description": "Martinique"},
    {"code": "03", "description": "Guyane"},
    {"code": "04", "description": "La Réunion"},
    {"code": "06", "description": "Mayotte"},
    {"code": "11", "description": "Île-de-France"},
    {"code": "24", "description": "Centre-Val de Loire"},
    {"code": "27", "description": "Bourgogne-Franche-Comté"},
    {"code": "28", "description": "Normandie"},
    {"code": "32", "description": "Hauts-de-France"},
    {"code": "44", "description": "Grand Est"},
    {"code": "52", "description": "Pays de la Loire"},
    {"code": "53", "description": "Bretagne"},
    {"code": "75", "description": "Nouvelle-Aquitaine"},
    {"code": "76", "description": "Occitanie"},
    {"code": "84", "description": "Auvergne-Rhône-Alpes"},
    {"code": "93", "description": "Provence-Alpes-Côte d'Azur"},
    {"code": "94", "description": "Corse"}
];

const tranchesEffectifs = [
    {"code": "NN", "description": "Unité non employeuse (pas de salarié au cours de l'année de référence et pas d'effectif au 31/12)"},
    {"code": "00", "description": "0 salarié (n'ayant pas d'effectif au 31/12 mais ayant employé des salariés au cours de l'année de référence)"},
    {"code": "01", "description": "1 ou 2 salariés"},
    {"code": "02", "description": "3 à 5 salariés"},
    {"code": "03", "description": "6 à 9 salariés"},
    {"code": "11", "description": "10 à 19 salariés"},
    {"code": "12", "description": "20 à 49 salariés"},
    {"code": "21", "description": "50 à 99 salariés"},
    {"code": "22", "description": "100 à 199 salariés"},
    {"code": "31", "description": "200 à 249 salariés"},
    {"code": "32", "description": "250 à 499 salariés"},
    {"code": "41", "description": "500 à 999 salariés"},
    {"code": "42", "description": "1 000 à 1 999 salariés"},
    {"code": "51", "description": "2 000 à 4 999 salariés"},
    {"code": "52", "description": "5 000 à 9 999 salariés"},
    {"code": "53", "description": "10 000 salariés et plus"}
];

const departements = [
    {"code": "01", "description": "Ain"},
    {"code": "02", "description": "Aisne"},
    {"code": "03", "description": "Allier"},
    {"code": "04", "description": "Alpes-de-Haute-Provence"},
    {"code": "05", "description": "Hautes-Alpes"},
    {"code": "06", "description": "Alpes-Maritimes"},
    {"code": "07", "description": "Ardèche"},
    {"code": "08", "description": "Ardennes"},
    {"code": "09", "description": "Ariège"},
    {"code": "10", "description": "Aube"},
    {"code": "11", "description": "Aude"},
    {"code": "12", "description": "Aveyron"},
    {"code": "13", "description": "Bouches-du-Rhône"},
    {"code": "14", "description": "Calvados"},
    {"code": "15", "description": "Cantal"},
    {"code": "16", "description": "Charente"},
    {"code": "17", "description": "Charente-Maritime"},
    {"code": "18", "description": "Cher"},
    {"code": "19", "description": "Corrèze"},
    {"code": "21", "description": "Côte-d'Or"},
    {"code": "22", "description": "Côtes-d'Armor"},
    {"code": "23", "description": "Creuse"},
    {"code": "24", "description": "Dordogne"},
    {"code": "25", "description": "Doubs"},
    {"code": "26", "description": "Drôme"},
    {"code": "27", "description": "Eure"},
    {"code": "28", "description": "Eure-et-Loir"},
    {"code": "29", "description": "Finistère"},
    {"code": "2A", "description": "Corse-du-Sud"},
    {"code": "2B", "description": "Haute-Corse"},
    {"code": "30", "description": "Gard"},
    {"code": "31", "description": "Haute-Garonne"},
    {"code": "32", "description": "Gers"},
    {"code": "33", "description": "Gironde"},
    {"code": "34", "description": "Hérault"},
    {"code": "35", "description": "Ille-et-Vilaine"},
    {"code": "36", "description": "Indre"},
    {"code": "37", "description": "Indre-et-Loire"},
    {"code": "38", "description": "Isère"},
    {"code": "39", "description": "Jura"},
    {"code": "40", "description": "Landes"},
    {"code": "41", "description": "Loir-et-Cher"},
    {"code": "42", "description": "Loire"},
    {"code": "43", "description": "Haute-Loire"},
    {"code": "44", "description": "Loire-Atlantique"},
    {"code": "45", "description": "Loiret"},
    {"code": "46", "description": "Lot"},
    {"code": "47", "description": "Lot-et-Garonne"},
    {"code": "48", "description": "Lozère"},
    {"code": "49", "description": "Maine-et-Loire"},
    {"code": "50", "description": "Manche"},
    {"code": "51", "description": "Marne"},
    {"code": "52", "description": "Haute-Marne"},
    {"code": "53", "description": "Mayenne"},
    {"code": "54", "description": "Meurthe-et-Moselle"},
    {"code": "55", "description": "Meuse"},
    {"code": "56", "description": "Morbihan"},
    {"code": "57", "description": "Moselle"},
    {"code": "58", "description": "Nièvre"},
    {"code": "59", "description": "Nord"},
    {"code": "60", "description": "Oise"},
    {"code": "61", "description": "Orne"},
    {"code": "62", "description": "Pas-de-Calais"},
    {"code": "63", "description": "Puy-de-Dôme"},
    {"code": "64", "description": "Pyrénées-Atlantiques"},
    {"code": "65", "description": "Hautes-Pyrénées"},
    {"code": "66", "description": "Pyrénées-Orientales"},
    {"code": "67", "description": "Bas-Rhin"},
    {"code": "68", "description": "Haut-Rhin"},
    {"code": "69", "description": "Rhône"},
    {"code": "70", "description": "Haute-Saône"},
    {"code": "71", "description": "Saône-et-Loire"},
    {"code": "72", "description": "Sarthe"},
    {"code": "73", "description": "Savoie"},
    {"code": "74", "description": "Haute-Savoie"},
    {"code": "75", "description": "Paris"},
    {"code": "76", "description": "Seine-Maritime"},
    {"code": "77", "description": "Seine-et-Marne"},
    {"code": "78", "description": "Yvelines"},
    {"code": "79", "description": "Deux-Sèvres"},
    {"code": "80", "description": "Somme"},
    {"code": "81", "description": "Tarn"},
    {"code": "82", "description": "Tarn-et-Garonne"},
    {"code": "83", "description": "Var"},
    {"code": "84", "description": "Vaucluse"},
    {"code": "85", "description": "Vendée"},
    {"code": "86", "description": "Vienne"},
    {"code": "87", "description": "Haute-Vienne"},
    {"code": "88", "description": "Vosges"},
    {"code": "89", "description": "Yonne"},
    {"code": "90", "description": "Territoire de Belfort"},
    {"code": "91", "description": "Essonne"},
    {"code": "92", "description": "Hauts-de-Seine"},
    {"code": "93", "description": "Seine-Saint-Denis"},
    {"code": "94", "description": "Val-de-Marne"},
    {"code": "95", "description": "Val-d'Oise"},
    {"code": "971", "description": "Guadeloupe"},
    {"code": "972", "description": "Martinique"},
    {"code": "973", "description": "Guyane"},
    {"code": "974", "description": "La Réunion"},
    {"code": "976", "description": "Mayotte"}
];