version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: koopany
    volumes:
    - .:/usr/local/apache2/htdocs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.koopany.rule=Host(`koopany.kodyssey.io`)"
      - "traefik.http.routers.koopany.entrypoints=websecure"
      - "traefik.http.routers.koopany.tls=true"
      - "traefik.http.services.koopany.loadbalancer.server.port=80"